sudo: false
addons:
  sonarcloud:
    token: ${SONAR_TOKEN}
jdk:
  - openjdk8
languaje: java
script:
  - mvn test
  - sonar-scanner -Dsonar.login=${SONAR_TOKEN} -Dsonar.organization=zerasul-github -Dsonar.projectKey=ejemploIC